Repository ComPWA/policy, pull requests merged in 2024-08, with the labels that each got.

#353 DX: enforce Ruff in Jupyter Lab
  src/compwa_policy/check_dev_files/__init__.py
  src/compwa_policy/check_dev_files/jupyter.py
Labels: 🖱️ DX

#354 DX: add `.envrc` for Conda and Pixi environments
  .cspell.json
  .envrc
  .vscode/settings.json
  src/compwa_policy/check_dev_files/__init__.py
  src/compwa_policy/check_dev_files/direnv.py
  src/compwa_policy/check_dev_files/vscode.py
  src/compwa_policy/utilities/__init__.py
Labels: ✨ Feature

#355 ENH: select `ALL` Ruff linting rules
  .cspell.json
  pyproject.toml
  src/compwa_policy/check_dev_files/__init__.py
  src/compwa_policy/check_dev_files/github_workflows.py
  src/compwa_policy/check_dev_files/release_drafter.py
  src/compwa_policy/check_dev_files/ruff.py
  src/compwa_policy/utilities/executor.py
  src/compwa_policy/utilities/precommit/__init__.py
  src/compwa_policy/utilities/pyproject/__init__.py
  src/compwa_policy/utilities/vscode.py
  src/compwa_policy/utilities/yaml.py
  tests/utilities/precommit/test_class.py
  tests/utilities/pyproject/test_setters.py
Labels: ⚙️ Enhancement

#356 ENH: add `display` as allowed function name
  src/compwa_policy/check_dev_files/ruff.py
Labels: ⚙️ Enhancement

#357 FIX: keep `black` in `doc` dependencies
  src/compwa_policy/check_dev_files/ruff.py
Labels: 🐛 Bug

#358 FIX: keep `black` in `doc` dependencies
  src/compwa_policy/check_dev_files/jupyter.py
Labels: 🐛 Bug

#359 FIX: do not insert empty list of rules
  src/compwa_policy/check_dev_files/ruff.py
Labels: 🐛 Bug

#360 DX: allow `dict` with keyword arguments in notebooks
  src/compwa_policy/check_dev_files/ruff.py
Labels: ⚙️ Enhancement

#362 ENH: automatically add `remove-empty-tag` hook
  src/compwa_policy/check_dev_files/__init__.py
  src/compwa_policy/check_dev_files/precommit.py
Labels: ⚙️ Enhancement

#363 DX: remove `editable` and `slideshow` from cell metadata
  src/compwa_policy/check_dev_files/nbstripout.py
Labels: ⚙️ Enhancement

#364 DX: highlight `.constraints/py*.txt` as pip requirements
  src/compwa_policy/check_dev_files/precommit.py
  src/compwa_policy/check_dev_files/vscode.py
  src/compwa_policy/utilities/python.py
Labels: ⚙️ Enhancement

#365 FIX: intelligently exclude Python files from `editorconfig`
  src/compwa_policy/check_dev_files/__init__.py
  src/compwa_policy/check_dev_files/editorconfig.py
  tests/check_dev_files/editorconfig/.pre-commit-config-good-no-python.yaml
  tests/check_dev_files/editorconfig/test_editorconfig.py
Labels: 🐛 Bug, ⚙️ Enhancement

#366 FEAT: implement `--allowed-cell-metadata` flag
  src/compwa_policy/check_dev_files/__init__.py
  src/compwa_policy/check_dev_files/nbstripout.py
Labels: ✨ Feature

#367 ENH: support `pixi` and `venv` in `.envrc`
  .cspell.json
  .envrc
  src/compwa_policy/.template/.cspell.json
  src/compwa_policy/check_dev_files/direnv.py
Labels: ✨ Feature

#368 FIX: set intermediate TOML tables to be super table
  src/compwa_policy/utilities/pyproject/setters.py
  tests/utilities/pyproject/test_setters.py
Labels: 🐛 Bug

#369 DX: remove GitPod configuration
  .gitpod.yml
  .pre-commit-config.yaml
  .vscode/extensions.json
  README.md
  src/compwa_policy/.template/.gitpod.yml
  src/compwa_policy/check_dev_files/gitpod.py
  src/compwa_policy/check_dev_files/vscode.py
Labels: 🖱️ DX, ⚙️ Enhancement

#370 MAINT: clean up Tox configuration
  pyproject.toml
  tox.ini
Labels: 🔨 Maintenance, 🖱️ DX

#371 BEHAVIOR: sort ComPWA/policy hooks right after `meta`
  src/compwa_policy/check_dev_files/precommit.py
Labels: ❗ Behavior

#372 BREAK: rename `enforce_multiline` in `to_toml_array()`
  src/compwa_policy/check_dev_files/ruff.py
  src/compwa_policy/check_dev_files/toml.py
  src/compwa_policy/utilities/toml.py
  tests/utilities/test_pyproject.py
  tests/utilities/test_toml.py
Labels: ⚠️ Interface

#373 ENH: allow enforce single-line arrays
  src/compwa_policy/utilities/toml.py
  tests/utilities/test_toml.py
Labels: ⚙️ Enhancement

#374 FEAT: automatically create Pixi environment
  .cspell.json
  .envrc
  .gitattributes
  .gitignore
  .vscode/settings.json
  environment.yml
  pyproject.toml
  src/compwa_policy/.template/.cspell.json
  src/compwa_policy/check_dev_files/__init__.py
  src/compwa_policy/check_dev_files/direnv.py
  src/compwa_policy/check_dev_files/pixi.py
  src/compwa_policy/utilities/__init__.py
  src/compwa_policy/utilities/pyproject/__init__.py
  tests/check_dev_files/test_pixi.py
Labels: ✨ Feature

#375 FEAT: create or remove Conda `environment.yml`
  src/compwa_policy/check_dev_files/__init__.py
  src/compwa_policy/check_dev_files/conda.py
  src/compwa_policy/check_dev_files/precommit.py
Labels: ✨ Feature

#376 BREAK: merge `vscode.remove_setting()` into `remove_settings()`
  docs/conf.py
  src/compwa_policy/check_dev_files/prettier.py
  src/compwa_policy/utilities/__init__.py
  src/compwa_policy/utilities/cfg.py
  src/compwa_policy/utilities/vscode.py
Labels: ⚠️ Interface

#377 FEAT: remove Pixi configuration if not listed in `--package-managers`
  docs/conf.py
  src/compwa_policy/check_dev_files/__init__.py
  src/compwa_policy/check_dev_files/conda.py
  src/compwa_policy/check_dev_files/pixi.py
  src/compwa_policy/utilities/__init__.py
  tests/check_dev_files/test_pixi.py
Labels: ✨ Feature

#380 ENH: add --drop-empty-cells tag in pre-commmit hook
  src/compwa_policy/check_dev_files/nbstripout.py
Labels: 📝 Docs, 🖱️ DX, ⚙️ Enhancement
