Repository ComPWA/policy, pull requests merged in 2025-01, with the labels that each got.

#479 ENH: remove cSpell configuration option if empty
  src/compwa_policy/check_dev_files/cspell.py
Labels: ⚙️ Enhancement

#480 FIX: wrap Tix `base` in list
  src/compwa_policy/check_dev_files/tox.py
Labels: 🐛 Bug

#469 DX: update Epic label to include emoji
  .github/workflows/sync-labels.yml
  labels/default.toml
  labels/physics.toml
Labels: 🖱️ DX

#482 FIX: replace `testenv:` with proper TOML table name
  src/compwa_policy/check_dev_files/tox.py
Labels: 🐛 Bug

#484 FIX: update link to `uv.lock` file explanation
  CONTRIBUTING.md
  src/compwa_policy/.template/CONTRIBUTING.md.jinja
Labels: 🐛 Bug, 📝 Docs

#485 FIX: remove `ci.skip` if empty
  src/compwa_policy/check_dev_files/precommit.py
Labels: 🐛 Bug

#486 FIX: remove `uv --locked` flag from RTD config
  src/compwa_policy/check_dev_files/readthedocs.py
Labels: ⚙️ Enhancement

#487 FIX: set `CODECOV_TOKEN`
  .github/workflows/ci.yml
  .vscode/settings.json
  codecov.yml
  pyproject.toml
  src/compwa_policy/check_dev_files/github_workflows.py
Labels: 🐛 Bug

#488 ENH: set `sphinx.configuration`
  pyproject.toml
  src/compwa_policy/check_dev_files/readthedocs.py
  tests/check_dev_files/readthedocs/extend/.readthedocs-bad.yml
  tests/check_dev_files/readthedocs/extend/.readthedocs-good.yml
  tests/check_dev_files/readthedocs/overwrite/.readthedocs-bad1.yml
  tests/check_dev_files/readthedocs/overwrite/.readthedocs-bad2.yml
  tests/check_dev_files/readthedocs/overwrite/.readthedocs-good.yml
Labels: ⚙️ Enhancement

#489 FIX: define label set with "💬 Meeting"
  .github/workflows/sync-labels.yml
  labels/meeting.toml
Labels: 🐛 Bug

#492 FIX: avoid Python 3.10 syntax
  pyproject.toml
  src/compwa_policy/utilities/pyproject/_struct.py
  src/compwa_policy/utilities/pyproject/setters.py
Labels: 🐛 Bug

#494 MAINT: remove `pygments` version constraint
  pyproject.toml
Labels: 🔨 Maintenance

#497 ENH: exclude `TYPE_CHECKING` from test coverage
  codecov.yml
  pyproject.toml
  src/compwa_policy/check_dev_files/pytest.py
  src/compwa_policy/utilities/pyproject/__init__.py
Labels: ⚙️ Enhancement

#498 DX: run tests with all python versions through Tox
  pyproject.toml
Labels: 🖱️ DX

#499 ENH: always overwrite kernel name to "Python 3 (ipykernel)"
  .cspell.json
  .pre-commit-hooks.yaml
  pyproject.toml
  src/compwa_policy/check_dev_files/precommit.py
  src/compwa_policy/set_nb_display_name.py
Labels: ⚙️ Enhancement

#500 ENH: update Tox labels and env_list
  src/compwa_policy/check_dev_files/__init__.py
  src/compwa_policy/check_dev_files/tox.py
Labels: ⚙️ Enhancement

#501 BEHAVIOR: add Pyton 3.13 to version classifiers
  pyproject.toml
  src/compwa_policy/utilities/pyproject/__init__.py
  src/compwa_policy/utilities/pyproject/getters.py
Labels: ❗ Behavior

#502 FIX: install `tox-uv` on RTD
  src/compwa_policy/check_dev_files/readthedocs.py
Labels: 🐛 Bug

#503 ENH: set Pyright venv to `.venv`
  src/compwa_policy/check_dev_files/pyright.py
  tests/check_dev_files/pyright/test_pyright.py
Labels: ⚙️ Enhancement

#505 ENH: add or remove `nbstripout` depending on `has_notebooks`
  src/compwa_policy/check_dev_files/__init__.py
  src/compwa_policy/check_dev_files/nbstripout.py
Labels: ⚙️ Enhancement

#506 FIX: add badges if `README.md` contains title only
  src/compwa_policy/utilities/readme.py
Labels: 🐛 Bug

#509 ENH: set Python path to `.venv/bin/python`
  .vscode/settings.json
  src/compwa_policy/check_dev_files/vscode.py
Labels: 🖱️ DX

#508 BREAK: rename `--no-macos` to `--macos-python-version`
  .github/workflows/ci.yml
  src/compwa_policy/check_dev_files/__init__.py
  src/compwa_policy/check_dev_files/github_workflows.py
Labels: ⚠️ Interface, ❗ Behavior

#511 FIX: set kernel name to "Pyproject Local"
  src/compwa_policy/set_nb_display_name.py
Labels: 🐛 Bug
